name: Test

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v2

    - uses: CyberAndrii/setup-steamcmd@v1

    - name: Generate auth code
      id: generate
      uses: ./
      with:
        shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}

    - name: Verify code length
      run: |
        code=${{ steps.generate.outputs.code }}
        [ ${#code} -ge 5 ] || exit 1
      shell: bash

    - name: Login
      run: steamcmd +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} ${{ steps.generate.outputs.code }} +quit
      shell: bash

